spring:
  application:
    name: anime-service

threads:
  virtual:
   enabled: true

web:
  error:
    include-stacktrace: on_param

server:
  servlet:
    context-path: /

  tomcat:
    threads:
      max: 20
