spring:
  application:
    name: anime-service

threads:
  virtual:
   enabled: true

logging:
  level:
    br.com.devdojo.spring_boot: debug

web:
  error:
    include-stacktrace: on_param

server:
  servlet:
    context-path: /

tomcat:
  threads:
    max: 20
